Nome  :     Construção Android
name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    version:  '2'
    env:
      ANDROID_HOME: ${{ github.actions.Cache }}/android
      GRADLE_HOME: ${{ github.actions.Cache }}/gradle
      PATH: $ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$GRADLE_HOME/bin:$PATH
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Android
        uses: android-actions/setup-android@v2
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
